name: mapscii
version: '0.3.1'
summary: The whole world in your console.
description: |
  A node.js based Vector Tile to Braille and ASCII renderer for
  xterm-compatible terminals.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
  mapscii:
    command: bin/mapscii
    plugs: [network]

parts:
  mapscii:
    source: .
    plugin: npm
    nodejs-version: '9.11.2'
    source-tag: 'v0.3.1'
